name: Re-Compile Sing-Box Rules

on:
  workflow_dispatch:

permissions:
  contents: write

env:
  SING_BOX_VERSION: 1.10.7

jobs:
  recompile_rules:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v3

    - name: Set up Git user
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"

    - name: Install sing-box
      run: |
        curl -Lo sing-box.tar.gz https://github.com/SagerNet/sing-box/releases/download/v${SING_BOX_VERSION}/sing-box-${SING_BOX_VERSION}-linux-amd64.tar.gz
        tar -xzf sing-box.tar.gz
        chmod +x sing-box-${SING_BOX_VERSION}-linux-amd64/sing-box
        sudo mv sing-box-${SING_BOX_VERSION}-linux-amd64/sing-box /usr/local/bin/sing-box
        sing-box version

    - name: Re-Compile and Overwrite Sing-Box Rules
      run: |
        find . -type f -name "*.srs" -exec bash -c '
        echo "Re-compiling: $1";
        if ! sing-box rule-set compile "$1" -o "$1"; then
          echo "Error compiling $1";
          exit 1;
        fi
        ' _ {} \;
        git add .
        if git diff-index --quiet HEAD --; then
          echo "No changes to commit";
          echo "No updates needed";
        else
          git commit -m "Re-compiled and overwritten sing-box rules";
          git push;
        fi

    - name: Clean up Sing-Box files
      run: |
        rm -rf sing-box-${SING_BOX_VERSION}-linux-amd64 sing-box.tar.gz
        echo "Cleaned up sing-box installation files"
